[package]
name = "wasbox"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
wast = "222.0.0"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.4"
wasabi_leb128 = "0.4.0"
num-traits = "0.2.19"