name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_default_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.1
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  build_all_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.1
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose --all-features --all-targets
      - name: Run tests
        run: cargo test --verbose --all-features --all-targets

  build_default_macos:
    runs-on: macos-latest
    steps:
      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: cmake
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: cargo build --verbose --all-features --all-targets
      - name: Run tests
        run: cargo test --verbose --all-features --all-targets

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake python3-dev swig
          version: 1.1
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
